### ISSUE TITLE
Charte de modération suggestions

### ISSUE THREAD

**Issue by margauxguillerm** [Logora/interface#39]
_Comment formuler une suggestion de débat ?_

Nous attachons une grande importance à vos contributions, c’est pourquoi nous vous offrons la possibilité de proposer des débats qui vous tiennent à cœur. Pour assurer des échanges enrichissants et respectueux, veuillez suivre attentivement les consignes suivantes :

**Neutralité :** Exprimez vos suggestions de manière neutre et objective, dépourvues de tout parti pris ou partialité.
**Ouverture au dialogue :** Veillez à ce que vos suggestions soient ouvertes à différentes interprétations, favorisant ainsi un débat équilibré.
**Question fermée :** Assurez-vous que le débat proposé puisse être répondu de manière binaire, par exemple oui/non, pour/contre, Paris/Marseille.
**Lisibilité :** Évitez les fautes d’orthographe et de grammaire, l’usage de métaphores ou d’expressions idiomatiques, pour une lecture et une compréhension fluides.
**Clarté :** Formulez vos suggestions de manière concise, précise et dépourvue d’ambiguïté.
**Pertinence :** Abordez des sujets pertinents et intéressants pour favoriser un échange fructueux.
**Courtoisie :** N’utilisez pas de langage vulgaire, insultant ou injurieux.

En cas de non-respect de cette charte, nous nous réservons le droit de ne pas publier votre suggestion.

**Comment by Mboulgour** [comment]
@pierrelaburthe
